name: 'Labeler'
description: 'Automatically label new pull requests based on the paths of files being changed'
author: 'GitHub'
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: false
    default: ${{ github.token }}
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: false
  sync-labels:
    description: 'Whether or not to remove labels when matching files are reverted'
    default: false
    required: false
  dot:
    description: 'Whether or not to auto-include paths starting with dot (e.g. `.github`)'
    default: false
    required: false
outputs:
  labels:
    description: 'A string containing the labels added, separated by white spaces. If no labels where added, it returns an empty string (`""`)'
  removed-labels:
    description: 'A string containing the labels removed, separated by white spaces. If no labels where removed, it returns an empty string (`""`)'
runs:
  using: 'node16'
  main: 'dist/index.js'
