name: 'Labeler'
description: 'Automatically label new pull requests based on the paths of files being changed'
author: 'GitHub'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: false
  sync-labels:
    description: 'Whether or not to remove labels when matching files are reverted'
    default: false
    required: false

outputs:
  new-labels:
    description: 'A comma-separated list of all new labels'
  all-labels:
    description: 'A comma-separated list of all labels that the PR contains'
runs:
  using: 'node12'
  main: 'dist/index.js'
