name: Check License Status

on:
  push:
    branches:
      - main
      - licensed_cache_update
  pull_request:
    branches:
      - main

jobs:
  check_license:
    needs: update_licenses_cache
    if: always() # always run after we update the license cache. if it failed, we will probably just fail as well
    runs-on: ubuntu-latest
    name: Check License Status
    steps:
      - uses: actions/checkout@v2
      - uses: jonabc/setup-licensed@v1.0.2
        with:
          version: '2.x'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: licensed status
