name: Update configuration files

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  call-update-configuration-files:
    name: Update configuration files
    uses: actions/reusable-workflows/.github/workflows/update-config-files.yml@main
